### PR TITLE
Convert between `Fixed` and `Rational`

### LINKED ISSUE #35: Convert between `Fixed` and `Rational`?

### PR DESCRIPTION
**Pull request by tfausak**
This fixes #35.

### CODE REVIEW

File: src/lib/Witch/Instances.hs [hunk 1]
```diff
@@ -907,6 +908,14 @@ instance From.From Rational Float where
 instance From.From Rational Double where
   from = fromRational
 
+-- | TODO
```
Comment (tfausak) [inline src/lib/Witch/Instances.hs:911]:
```suggestion
-- | Uses `fromRational` as long as there isn't a loss of precision.
```

File: src/lib/Witch/Instances.hs [hunk 2]
```diff
@@ -907,6 +908,16 @@ instance From.From Rational Float where
 instance From.From Rational Double where
   from = fromRational
 
+-- | Uses `fromRational` as long as there isn't a loss of precision.
+instance Fixed.HasResolution a => TryFrom.TryFrom Rational (Fixed.Fixed a) where
+  tryFrom = Utility.eitherTryFrom $ \s ->
+    let
+      t :: Fixed.Fixed a
+      t = fromRational s
+    in if toRational t == s
```
Comment (tfausak) [inline src/lib/Witch/Instances.hs:917]: I would prefer a more direct way to tell if the conversion would lose precision, but I couldn't think of anything.

**Comment by tfausak** [comment]
I considered using `Ratio a` rather than `Rational`, but it didn't seem worth the effort at this point. The precision for `Fixed` values is given as an `Integer`, so using `Rational` was simple.
